routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;


Auth::routes();
Route::get('/', 'website\HomeController@index');
Route::view('/about', 'about');


Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/register-types', 'Auth\RegisterController@types');
Route::get('/needy-register', 'Auth\RegisterController@needyRegister');
Route::post('/needy-register', 'Auth\RegisterController@needyCreate');
Route::get('/donator-register', 'Auth\RegisterController@donatorRegister');
Route::post('/donator-register', 'Auth\RegisterController@donatorCreate');

Route::group(['middleware' => ['web']], function () {
});
Route::group(['middleware' => ['auth']], function () {
    Route::get('/profile', 'website\UsersController@profile');
    Route::post('/donation/store', 'website\HomeController@donationStore');
    Route::get('/donation/request/{id}', 'website\HomeController@donationRequest');
    Route::get('/donation/deliver/{id}', 'website\HomeController@donationDeliver');
    Route::get('/order/deliver/{id}', 'website\HomeController@orderDeliver');
    Route::get('/posts/{id}', 'website\PostsController@getPost');
    Route::get('/home', 'website\HomeController@home');



});



Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/employees', 'admin\EmployeesController');
    Route::resource('/admins', 'admin\AdminsController');
    Route::resource('/donators', 'admin\DonatorsController');
    Route::resource('/donations', 'admin\DonationsController');
    Route::resource('/orders', 'admin\OrdersController');
    Route::get('/donations/{id}/assign/create', 'admin\DonationsController@createAssign');
    Route::post('/donations/{id}/assign/store', 'admin\DonationsController@storeAssign');
    Route::get('/orders/{id}/assign/create', 'admin\OrdersController@createAssign');
    Route::post('/orders/{id}/assign/store', 'admin\OrdersController@storeAssign');
    Route::get('/orders/{id}/approve', 'admin\OrdersController@approve');
    Route::get('/orders/{id}/reject', 'admin\OrdersController@reject');
    Route::resource('/needy', 'admin\NeedyController');
    Route::resource('/categories', 'admin\CategoriesController');
    Route::resource('/posts', 'admin\PostsController');
    Route::get('/get-product-category-data/{product_id}/{category_id}', 'admin\ProductsController@ProductData');
    Route::resource('/sliders', 'admin\SlidersController');
    Route::resource('/user/{id}/rates', 'admin\RatesController');
    Route::get('/send-email', 'admin\UsersController@sendEmail');
    Route::post('/store-email', 'admin\UsersController@storeEmail');



});

app/Http/Controllers/admin/DonatorsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DonatorsController extends Controller
{
    public function index()
    {
        $donators = User::where('role',4)->get();

        return view('admin.donators.index', compact('donators'));
    }





    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.donators.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'f_name' => 'required',
            'l_name' => 'required',
            'phone' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required',
            'address' => 'required',
        ]);
        $donator = User::create([
            'f_name' => $request->f_name,
            'l_name' => $request->l_name,
            'email' => $request->email,
            'phone' => $request->phone,
            'address' => $request->address,
            'password' => Hash::make($request->password),
            'role' => 4,
        ]);
        if ($request->hasFile('photo')) {
            $request->validate([
                'photo' => 'image|mimes:jpeg,png,jpg,gif,svg'
            ]);

            $imageName = Str::random(10). '.' . $request->file('photo')->extension();
            $request->file('photo')->move(
                base_path() . '/public/uploads/profiles/', $imageName
            );
            $donator->photo = '/uploads/profiles/' . $imageName;
            $donator->save();

        }


        return redirect('/webadmin/donators')->withFlashMessage(json_encode(['success' => true, 'msg' => 'Donator Added Successfully']));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $donator = User::where('id', $id)->first();
        return view('admin.donators.show', compact('donator'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $donator = User::where('id', $id)->first();
        return view('admin.donators.edit', compact('donator'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'f_name' => 'required',
            'l_name' => 'required',
            'phone' => 'required',
            'address' => 'required',


        ]);
        $donator = User::where('id', $id)->first();

        if ($request->email != $donator->email) {
            $this->validate($request, [
                'email' => 'email|unique:users',
            ]);
            $donator->update([
                'email' => $request->email
            ]);

        }
        $donator->update([
            'f_name' => $request->f_name,
            'l_name' => $request->l_name,
            'phone' => $request->phone,
            'address' => $request->address,

        ]);

        if ($request->password != '') {
            $donator->update([
                'password' => Hash::make($request->password),
            ]);
        }
        if ($request->hasFile('photo')) {
            $request->validate([

                'photo' => 'image|mimes:jpeg,png,jpg,gif,svg'

            ]);

            $imageName = Str::random(10) . '.' . $request->file('photo')->extension();
            $request->file('photo')->move(
                base_path() . '/public/uploads/profiles/', $imageName
            );
            $donator->photo = '/uploads/profiles/' . $imageName;
            $donator->save();

        }


        return redirect('/webadmin/donators' )->withFlashMessage(json_encode(['success' => true, 'msg' => 'Donator Edited Successfully']));


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $donator = User::where('id', $id)->first();
        $donator->delete();
        return redirect()->back()->withFlashMessage(json_encode(['success' => true, 'msg' => 'Donator Deleted Successsfully']));
    }

}

resources/views/admin/donators/add.blade.php
@extends('admin.layouts.app')

@section('title')
   Add Donator
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Dashboard</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/donators')}}" class="m-menu__link">
            <span class="m-menu__link-text">Donators</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">Add Donator</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')



@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                       Add Donator
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/donators" method="post" enctype="multipart/form-data" >
            <div class="m-portlet__body">
                @csrf
                @include('admin.donators.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">Add</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')



@endsection

resources/views/admin/donators/edit.blade.php
@extends('admin.layouts.app')

@section('title')
   Eidt Donator
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Dashboard</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/donators')}}" class="m-menu__link">
            <span class="m-menu__link-text">Donators</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text"> Edit Donator</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        Edit Donator
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($donator,['route' => ['donators.update' , $donator->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">

            @include('admin.donators.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">Edit</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/donators/form.blade.php
<div class="form-group m-form__group row">
    <label class="col-lg-1 col-form-label"> First Name</label>
    <div class="col-lg-3{{ $errors->has('f_name') ? ' has-danger' : '' }}">
        {!! Form::text('f_name',old('f_name'),['class'=>'form-control m-input','autofocus','placeholder'=> 'First Name' ]) !!}
        @if ($errors->has('f_name'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('f_name ') }}</strong>
            </span>
        @endif
    </div>
    <label class="col-lg-1 col-form-label">Last Name</label>
    <div class="col-lg-3{{ $errors->has('l_name') ? ' has-danger' : '' }}">
        {!! Form::text('l_name',old('l_name'),['class'=>'form-control m-input','placeholder'=> 'Last Name' ]) !!}
        @if ($errors->has('l_name'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('l_name') }}</strong>
            </span>
        @endif
    </div>
    <label class="col-lg-1 col-form-label">Phone</label>
    <div class="col-lg-3{{ $errors->has('phone') ? ' has-danger' : '' }}">
        {!! Form::text('phone',old('phone'),['class'=>'form-control m-input','placeholder'=> 'Phone Number' ]) !!}
        @if ($errors->has('phone'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('phone') }}</strong>
            </span>
        @endif
    </div>

</div>


<div class="form-group m-form__group row">

    <label class="col-lg-1 col-form-label">Email</label>
    <div class="col-lg-5{{ $errors->has('email') ? ' has-danger' : '' }}">
        {!! Form::text('email',old('email'),['class'=>'form-control m-input','placeholder'=> 'Email' ]) !!}
        @if ($errors->has('email'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('email') }}</strong>
            </span>
        @endif
    </div>
    <label class="col-lg-1 col-form-label">Password</label>
    <div class="col-lg-5{{ $errors->has('password') ? ' has-danger' : '' }}">
        {!! Form::password('password',['class'=>'form-control m-input','placeholder'=> 'Password' ]) !!}
        @if ($errors->has('password'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('password') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
    <label class="col-lg-1 col-form-label">Address</label>
    <div class="col-lg-11{{ $errors->has('address') ? ' has-danger' : '' }}">
        {!! Form::text('address',old('address'),['class'=>'form-control m-input','placeholder'=> 'Address' ]) !!}
        @if ($errors->has('address'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('address') }}</strong>
            </span>
        @endif
    </div>

</div>





<div class="form-group m-form__group row">
    <label class="col-lg-1 col-form-label">Photo</label>
    <div class="col-lg-11{{ $errors->has('photo') ? ' has-danger' : '' }}">

        <input type="file" name="photo"   class="form-control uploadinput">
        @if ($errors->has('photo'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('photo') }}</strong>
            </span>
        @endif
    </div>

</div>
@if($donator ?? '' && $donator->photo)
<div class="row">




            <div class="col-lg-6 col-md-6 col-sm-6" style="margin-bottom: 10px;">

                <img
                        data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                        alt="First slide [800x4a00]"
                        src="{{asset($donator->photo)}}"
                        style="height: 150px; width: 150px"
                        data-holder-rendered="true">
            </div>

</div>
@endif

resources/views/admin/donators/index.blade.php
@extends('admin.layouts.app')
@section('title')
    Donators
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Dashboard</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/donators')}}" class="m-menu__link">
            <span class="m-menu__link-text">Donators</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>


@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        Donators
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('donators.create')}}" style="margin-bottom:20px"
                    class="btn btn_primary btn btn-danger"><i class=" fa fa-edit"></i>Add Donator</a></div>
            <br>


            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable search_result"
                   id="m_table_testArea">

                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Address</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($donators as $index=> $donator)
                    <tr>
                        <td>{{++$index}}</td>
                        <td>{{$donator->f_name}} {{$donator->l_name}} </td>
                        <td>{{$donator->email}} </td>
                        <td>{{$donator->phone}} </td>
                        <td>{{$donator->address}} </td>
                        <td>


                            <a title="Show" href="/webadmin/donators/{{$donator->id}}"><i class="fa fa-eye"></i></a>
                            <a title="Edit" href="/webadmin/donators/{{$donator->id}}/edit"><i class="fa fa-edit"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/donators/{{ $donator->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete"/>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/testArea/script.js') !!}--}}

@endsection

resources/views/admin/donators/show.blade.php
@extends('admin.layouts.app')

@section('title')
    Donator Details
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">Dashboard</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/donators')}}" class="m-menu__link">
            <span class="m-menu__link-text">Donators</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">Donator Details </span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        Donator Details
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($donator,['route' => ['donators.show' , $donator->id],'method'=> 'get','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">


            <div class="form-group m-form__group row">
                <label class="col-lg-1 col-form-label">First Name</label>
                <div class="col-lg-3{{ $errors->has('f_name') ? ' has-danger' : '' }}">
                    {!! Form::text('f_name',old('f_name'),['class'=>'form-control m-input','autofocus','disabled' ]) !!}

                </div>
                <label class="col-lg-1 col-form-label">Last Name</label>
                <div class="col-lg-3{{ $errors->has('l_name') ? ' has-danger' : '' }}">
                    {!! Form::text('l_name',old('l_name'),['class'=>'form-control m-input','disabled' ]) !!}

                </div>
                <label class="col-lg-1 col-form-label">Phone</label>
                <div class="col-lg-3{{ $errors->has('phone') ? ' has-danger' : '' }}">
                    {!! Form::text('phone',old('phone'),['class'=>'form-control m-input','disabled' ]) !!}

                </div>


            </div>


            <div class="form-group m-form__group row">

                <label class="col-lg-2 col-form-label">Email</label>
                <div class="col-lg-5{{ $errors->has('email') ? ' has-danger' : '' }}">
                    {!! Form::text('email',old('email'),['class'=>'form-control m-input','disabled' ]) !!}

                </div>


            </div>
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">Address</label>
                <div class="col-lg-5{{ $errors->has('address') ? ' has-danger' : '' }}">
                    <input type="text" class="form-control m-input" value="{{$donator->address}}" disabled="">

                </div>



            </div>


            @if(isset($donator) && $donator->photo)
                <div class="row">


                    <div class="col-lg-6 col-md-6 col-sm-6" style="margin-bottom: 10px;">

                        <img
                            data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                            alt="First slide [800x4a00]"
                            src="{{asset($donator->photo)}}"
                            style="height: 150px; width: 150px"
                            data-holder-rendered="true">
                    </div>

                </div>
            @endif



        </div>

    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection